# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u5f52\u6863\u540d\u79f0')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\u5f52\u6863',
                'verbose_name_plural': '\u5f52\u6863',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('title', models.CharField(default='', error_messages={'max_length': '\u6807\u9898\u592a\u957f\u4e86'}, help_text='\u957f\u5ea6\u572850\u5b57\u4ee5\u5185', max_length=30, verbose_name='\u535a\u6587\u6807\u9898')),
                ('cover', models.ImageField(blank=True, max_length=50, upload_to=b'', verbose_name='\u5c01\u9762')),
                ('content_raw', models.TextField(default='', verbose_name='\u535a\u6587\u5185\u5bb9\uff08markdown\u683c\u5f0f\uff09')),
                ('content_html', models.TextField(blank=True, default='', editable=False, verbose_name='\u535a\u6587\u5185\u5bb9\uff08html\u683c\u5f0f\uff09')),
                ('is_markdown', models.BooleanField(default=False, help_text='\u8bed\u6cd5\u8be6\u89c1http://www.appinn.com/markdown/', verbose_name='\u4f7f\u7528Markdown\u8bed\u6cd5\u4e66\u5199')),
                ('slug', models.SlugField(unique=True)),
                ('allow_comment', models.BooleanField(default=True, verbose_name='\u5141\u8bb8\u8bc4\u8bba')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='\u5f52\u6863')),
            ],
            options={
                'db_table': 'post',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u6807\u7b7e')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'tag',
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('title', 'created_at', 'author')]),
        ),
    ]
