# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sequence',
            field=models.SmallIntegerField(default=0, help_text='\u6570\u5b57\u8d8a\u5927\u8d8a\u9760\u524d\uff0c\u9ed8\u8ba4\u6700\u5927999', verbose_name='\u6392\u5e8f\u53f7'),
        ),
    ]
