# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151221_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aaa', related_query_name='bbb', to='blog.Author'),
        ),
    ]
