# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151224_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='', max_length=50, upload_to=b'', verbose_name='\u5c01\u9762'),
            preserve_default=False,
        ),
    ]
