# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, max_length=50, upload_to=b'', verbose_name='\u5c01\u9762'),
        ),
    ]
