# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20151225_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, height_field=10, max_length=50, upload_to=b'', verbose_name='\u5c01\u9762', width_field=10),
        ),
    ]
